---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cfplatformeng/tile-generator
    tag: v12.0.4
inputs:
- name: gcp-service-broker-ci
- name: gcp-service-broker
  path: src/gcp-service-broker
- name: version

outputs:
- name: candidate

run:
  path: gcp-service-broker-ci/ci/tasks/build-tile.sh
