---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: alpine
inputs:
- name: gcp-service-broker-ci
- name: gcp-service-broker
- name: metadata
- name: tiles
- name: client-linux
- name: client-windows
- name: client-darwin
- name: helm-chart
outputs:
- name: bundle
run:
  path: gcp-service-broker-ci/ci/tasks/bundle.sh
